# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.78356062 0.95305918 0.76062171]
  [0.05464266 0.35689387 0.05051455]
  [0.30805568 0.85288205 0.54668754]]

 [[0.84349177 0.01470174 0.24780559]
  [0.73314033 0.24893145 0.53281199]
  [0.98236775 0.91205051 0.76424568]]

 [[0.4441264  0.45133067 0.71871907]
  [0.78942532 0.95063404 0.78972187]
  [0.2890871  0.29320669 0.13304395]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
import numpy as np
x = np.diag([0,1,2, 3, 4])
print(x)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
x = np.ones((1,1))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.16245509 0.8556113  0.25855818 0.47294172 0.82053503]
 [0.44919329 0.56499493 0.89818684 0.07904337 0.67424235]
 [0.98915766 0.79566438 0.1100111  0.50791825 0.41701823]
 [0.91682577 0.58667859 0.02008935 0.45005282 0.56796215]
 [0.73163122 0.33631567 0.69182682 0.70369563 0.81286156]]
After normalization:
[[0.14690991 0.86219097 0.24608051 0.46730696 0.8259951 ]
 [0.4428005  0.56229841 0.90612548 0.06083577 0.6750329 ]
 [1.         0.80033061 0.09279196 0.5033999  0.40959845]
 [0.92535934 0.5846742  0.         0.44368747 0.56536035]
 [0.73425357 0.32631995 0.69317866 0.7054263  0.8180767 ]]


# 5.  How to find common values between two arrays?

In [1]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
import numpy as np
x = np.random.randint(0,2,6)
print("A:")
print(x)
y = np.random.randint(0,2,6)
print("B:")
print(y)
print("Test above two arrays are equal")
array_equal = np.allclose(x, y)
print(array_equal)

A:
[0 1 0 1 0 1]
B:
[1 0 0 1 1 0]
Test above two arrays are equal
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [3]:
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by zero:")
print(x)

Original array:
[0.97920658 0.95107351 0.34383956 0.77463151 0.44924945 0.66373824
 0.54430564 0.86096898 0.23255529 0.56495573 0.05473039 0.04698811
 0.54163192 0.09967224 0.06573236]
Maximum value replaced by zero:
[0.         0.95107351 0.34383956 0.77463151 0.44924945 0.66373824
 0.54430564 0.86096898 0.23255529 0.56495573 0.05473039 0.04698811
 0.54163192 0.09967224 0.06573236]


# 9. How to print all the values of an array?

In [11]:
import numpy as np
import sys
nums = np.arange(10+1)
np.set_printoptions(threshold=sys.maxsize)
print(nums)

[ 0  1  2  3  4  5  6  7  8  9 10]


# 10.Subtract the mean of each row of a matrix

In [9]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.79081509 0.47951334 0.67884179 0.81301437 0.06950939 0.982298
  0.17342412 0.4465945  0.43232308 0.72541512]
 [0.63673634 0.98966352 0.96694075 0.3907455  0.23861704 0.49179743
  0.77872474 0.24749359 0.56296372 0.50875379]
 [0.81126292 0.98568037 0.13104092 0.38050493 0.50842072 0.00791861
  0.49444186 0.98530773 0.22565574 0.31343328]
 [0.22168075 0.76741627 0.61747654 0.60132005 0.91343651 0.25523918
  0.50765012 0.9985174  0.05288372 0.18352949]
 [0.03971454 0.38672623 0.67336562 0.7902458  0.90975572 0.06437084
  0.42152016 0.06301214 0.52442354 0.13431247]]

Subtract the mean of each row of the matrix:

[[ 0.23164021 -0.07966154  0.11966691  0.25383949 -0.48966549  0.42312312
  -0.38575076 -0.11258038 -0.1268518   0.16624024]
 [ 0.0554927   0.40841988  0.38569711 -0.19049814 -0.3426266  -0.08944621
   0.19748109 -0.33375005 -0.01827992 -0.07248986]
 [ 0.32689622  0.50131366 -0.35332579 -0.10386178  0.02405402 -0.4764481
   0.01007515  0.50094102 -0.25871096 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
import numpy as np
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 1])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

Original vector:
[1 1 1]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


# 12.How to get the diagonal of a dot product?

In [34]:
a = np.random.randint(1, 2, (3,3))
b = np.random.randint(4, 8, (3,3))
a.dot(b)
np.diagonal(a.dot(b))
print(a,b)

[[1 1 1]
 [1 1 1]
 [1 1 1]] [[4 6 4]
 [6 7 4]
 [4 5 4]]


# 13.How to find the most frequent value in an array?

In [12]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array is number:")
print(np.bincount(x).argmax())

Original array:
[5 6 5 8 1 5 7 4 8 6 0 7 4 5 9 0 6 4 3 7 4 5 2 7 6 8 2 4 5 0 0 1 3 4 1 6 3
 2 6 2]
Most frequent value in the above array:
4


# 14.How to get the n largest values of an array

In [16]:
import numpy as np
x = np.arange(10)
print("Original array:",x)
print("Largest Value in array is","=",x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array: [0 1 2 3 4 5 6 7 8 9]
Largest Value in array is = [0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [35]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array([10,20,30,40])
a3=np.array([5,6,7,8])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 10, 5)
(2, 20, 6)
(3, 30, 7)
